---
deployment:
  tasks:
    # =====================================
    # 1. DEPLOY CORE LARAVEL (TANPA public)
    # =====================================
    - export DEPLOYPATH=/home/malahpho1/wedding
    - /bin/rsync -av --delete --exclude='public' ./ $DEPLOYPATH/

    # =====================================
    # 2. DEPLOY ISI public KE SUBDOMAIN
    # =====================================
    - export PUBLICPATH=/home/malahpho1/public_html/wedding-pipit-pael.malahphotobooth.com
    - /bin/rsync -av --delete ./public/ $PUBLICPATH/
